# Generated by Django 3.1.4 on 2020-12-20 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favourite',
            field=models.CharField(db_column='Favourite', default='', max_length=30),
        ),
    ]
