# Generated by Django 3.1.4 on 2020-12-20 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201220_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='favourite',
        ),
        migrations.CreateModel(
            name='UserFavourite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favourite', models.CharField(db_column='Favourite', max_length=100)),
                ('user', models.ForeignKey(db_column='User', on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
